# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
x1 = np.array([1,2])

# Create a 2-dimensional NumPy array using np.array()
x2 = np.array([[1,2],[3,4]])

# Create a 3-dimensional Numpy array using np.array()
x3 = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(f'''x1
dimension: {x1.shape}
Data type: {x1.dtype}
Size: {x1.size}
Type: {type(x1)}''')

x1
dimension: (2,)
Data type: int32
Size: 2
Type: <class 'numpy.ndarray'>


In [4]:
# Attributes of 2-dimensional array
print(f'''x2
dimension: {x2.shape}
Data type: {x2.dtype}
Size: {x2.size}
Type: {type(x2)}''')

x2
dimension: (2, 2)
Data type: int32
Size: 4
Type: <class 'numpy.ndarray'>


In [5]:
# Attributes of 3-dimensional array
print(f'''x3
dimension: {x3.shape}
Data type: {x3.dtype}
Size: {x3.size}
Type: {type(x3)}''')

x3
dimension: (2, 2, 2)
Data type: int32
Size: 8
Type: <class 'numpy.ndarray'>


In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df_x1 = pd.DataFrame(x1)
df_x1

0
0  1
1  2

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[2, 4],
       [5, 7],
       [9, 5],
       [2, 1],
       [3, 4],
       [4, 5],
       [0, 8]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.44431255, 0.90793449, 0.31998087, 0.56218806, 0.6500157 ],
       [0.46353674, 0.79587077, 0.4772226 , 0.55137186, 0.5777007 ],
       [0.64241996, 0.37153386, 0.27265885, 0.16984452, 0.43592377]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array = np.random.randint(1, 10, size=(3,7))


# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 7, 9])

In [14]:
# Find the 0'th index of the latest array you created
array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
array[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2, :2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array = np.random.randint(10, size=(3,5))
ones = np.ones((3,5))
array

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [18]:
# Add the two arrays together
new_array = array + ones
new_array

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5,3))

In [20]:
# Try add the array of ones and the other most recent array together
new_array = new_array + ones
new_array

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [25]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))

In [26]:
# Subtract the new array of ones from the other most recent array
new_array = new_array - ones
new_array

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [27]:
# Multiply the ones array with the latest array
new_array = new_array * ones
new_array

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [28]:
# Take the latest array to the power of 2 using '**'
new_array = new_array**2
new_array

array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [29]:
# Do the same thing with np.square()
new_array = np.square(new_array)
new_array

array([[1.296e+03, 2.401e+03, 1.600e+01, 0.000e+00, 8.100e+01],
       [1.000e+00, 2.401e+03, 8.100e+01, 1.000e+00, 6.250e+02],
       [6.250e+02, 6.561e+03, 8.100e+01, 6.250e+02, 1.000e+00]])

In [31]:
# Find the mean of the latest array using np.mean()
mean = np.mean(new_array)
mean

986.4

In [32]:
# Find the maximum of the latest array using np.max()
maximum = np.max(new_array)
maximum

6561.0

In [33]:
# Find the minimum of the latest array using np.min()
minimum = np.min(new_array)
minimum

0.0

In [35]:
# Find the standard deviation of the latest array
deviation = np.std(new_array)
deviation

1690.2264463674683

In [36]:
# Find the variance of the latest array
var = np.var(new_array)
var

2856865.44

In [37]:
# Reshape the latest array to (3, 5, 1)
new_array.reshape(3,5,1)

array([[[1.296e+03],
        [2.401e+03],
        [1.600e+01],
        [0.000e+00],
        [8.100e+01]],

       [[1.000e+00],
        [2.401e+03],
        [8.100e+01],
        [1.000e+00],
        [6.250e+02]],

       [[6.250e+02],
        [6.561e+03],
        [8.100e+01],
        [6.250e+02],
        [1.000e+00]]])

In [38]:
# Transpose the latest array
new_array.T

array([[1.296e+03, 1.000e+00, 6.250e+02],
       [2.401e+03, 2.401e+03, 6.561e+03],
       [1.600e+01, 8.100e+01, 8.100e+01],
       [0.000e+00, 1.000e+00, 6.250e+02],
       [8.100e+01, 6.250e+02, 1.000e+00]])

What does the transpose do?

In [41]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(10, size=(3,3))
array2 = np.random.randint(10, size=(3,2))
print(array1)
print(array2)

[[1 4 7]
 [9 8 8]
 [0 8 6]]
[[8 7]
 [0 7]
 [7 2]]


In [46]:
# Perform a dot product on the two newest arrays you created
np.dot(array1, array2)

array([[ 57,  49],
       [128, 135],
       [ 42,  68]])

In [48]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array1 = np.random.randint(10, size=(4,3))
array2 = np.random.randint(10, size=(4,3))

In [49]:
# Perform a dot product on the two newest arrays you created
np.dot(array1, array2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [50]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array1, array2.T)

array([[  7,  56,  28,  14],
       [ 14,  40,  36,  10],
       [ 69, 153, 111,  57],
       [ 62, 140, 100,  52]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [58]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(10, size=(3,2))
array2 = np.random.randint(10, size=(3,2))
print(array1)
print(array2)

[[6 0]
 [3 3]
 [4 6]]
[[6 3]
 [6 2]
 [5 1]]


In [59]:
# Compare the two arrays with '>'
array1 > array2

array([[False, False],
       [False,  True],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [53]:
# Compare the two arrays with '>='
array1 >= array2

array([[False, False],
       [False, False],
       [False,  True]])

In [54]:
# Find which elements of the first array are greater than 7
array1 > 7

array([[False, False],
       [False, False],
       [False,  True]])

In [55]:
# Which parts of each array are equal? (try using '==')
array1 == array2

array([[False, False],
       [False, False],
       [False, False]])

In [60]:
# Sort one of the arrays you just created in ascending order
np.sort(array1)

array([[0, 6],
       [3, 3],
       [4, 6]])

In [61]:
# Sort the indexes of one of the arrays you just created
np.argsort(array1)

array([[1, 0],
       [0, 1],
       [0, 1]], dtype=int64)

In [63]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array1)

0

In [64]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array1)

1

In [65]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array1, axis = 1)

array([0, 0, 1], dtype=int64)

In [66]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array1, axis = 0)

array([1, 0], dtype=int64)

In [67]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[-1.46696789,  0.89262947, -0.10525713, -0.95534644, -0.41476463],
       [-1.39874088, -0.34408054,  0.75078589, -0.32762518, -0.86159805],
       [-0.2581848 ,  0.46095562, -1.34938997, -1.01907279,  0.12701224]])

In [68]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.